- name: update
  apt:
    force_apt_get: yes
    update_cache: yes

- name: dist-upgrade
  apt:
    force_apt_get: yes
    upgrade: dist

- name: autoremove
  apt:
    force_apt_get: yes
    autoremove: yes

- name: autoclean
  apt:
    force_apt_get: yes
    autoclean: yes
