- name: Install dependencies
  apt:
    force_apt_get: yes
    name:
      - ca-certificates
      - software-properties-common
      - curl
      - gnupg

# free-form (string) arguments, all arguments on one line
- name: define Keyring File
  ansible.builtin.command: install -m 0755 -d /etc/apt/keyrings
  become: true

- name: curl gpg Key
  ansible.builtin.command: curl -fsSL https://download.docker.com/linux/raspbian/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg

- name: changmod of File
  ansible.builtin.command: chmod a+r /etc/apt/keyrings/docker.gpg
  become: true

- name: Set up Dockers APT repository
  ansible.builtin.command: echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/raspbian $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  
- name: Update apt packages
  apt:
    force_apt_get: yes
    autoclean: yes
    autoremove: yes
    update_cache: yes
    upgrade: dist

- name: Install Docker
  apt:
    force_apt_get: yes
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
      - python3-setuptools
      - python3-pip
    install_recommends: no

- name: Install Docker SDK for python
  pip:
    name: docker

- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    append: yes
    groups: docker

- name: Enable Docker IPv6
  copy:
    dest: /etc/docker/daemon.json
    mode: 0600
    content: |
      {
        "ipv6": true,
        "fixed-cidr-v6": "2001:db8:1::/64"
      }
  notify: Restart Docker

- name: Flush handlers
  meta: flush_handlers
