- name: Create pihole directory
  file:
    path: /home/pi/pihole
    owner: pi
    group: pi
    state: directory
    mode: 0755

- name: Get IPv6
  set_fact:
    ipv6: "{{ item }}"
  with_items: "{{ ansible_all_ipv6_addresses }}"
  when: "item.startswith('fd00')"

- name: Start/Update pihole container
  docker_container:
    name: pihole
    hostname: "{{ inventory_hostname }}"
    image: pihole/pihole:v5.1.1
    restart_policy: unless-stopped
    env:
      TZ: "Europe/Berlin"
      ServerIP: "{{ ansible_host }}"
      ServerIPv6: "{{ ipv6 }}"
      WEBPASSWORD: "{{ pihole_webpassword }}"
      DNS1: "1.1.1.1"
      DNS2: "2606:4700:4700::1111"
      VIRTUAL_HOST: "{{ inventory_hostname }}"
      DNSMASQ_LISTENING: "local"
    dns_servers:
      - 127.0.0.1
      - 1.1.1.1
    network_mode: host
    volumes:
      - /home/pi/pihole/pihole/:/etc/pihole/
      - /home/pi/pihole/dnsmasq.d/:/etc/dnsmasq.d/
    log_driver: json-file
    log_options:
      max-size: "10m"
      max-file: "5"

- name: Check pihole container
  uri:
    url: http://localhost
  register: result
  until: result.status == 200
  retries: 5
  delay: 10

- name: Remove old image versions
  docker_prune:
    images: yes
    images_filters:
      dangling: false

- name: ATTENTION!!!
  debug:
    msg:
      - "Make sure to point your DNS server settings to this Pi-hole:"
      - "DNSv4: {{ ansible_host }}"
      - "DNSv6: {{ ipv6 }}"
