- name: Create pihole directory
  file:
    path: /home/pi/pihole
    owner: pi
    group: pi
    state: directory
    mode: 0755

- name: Create 2nd pihole directory
  file:
    path: /home/pi/pihole/pihole
    state: directory

- name: Create FTL config
  blockinfile:
    path: /home/pi/pihole/pihole/pihole-FTL.conf
    create: yes
    block: MAXDBDAYS={{ pihole_ftl_max_db_days }}

- name: Get IPv6
  set_fact:
    ipv6: "{{ item }}"
  with_items: "{{ ansible_all_ipv6_addresses }}"
  when: "item.startswith('fd00')"

- name: Start/Update pihole container
  docker_container:
    name: pihole
    hostname: "{{ inventory_hostname }}"
    image: "{{ pihole_image }}"
    restart_policy: unless-stopped
    env:
      TZ: "{{ timezone }}"
      ServerIP: "0.0.0.0"
      ServerIPv6: "::"
      WEBPASSWORD: "{{ pihole_webpassword }}"
      PIHOLE_DNS_: "{{ pihole_dns }}"
      VIRTUAL_HOST: "{{ inventory_hostname }}"
      DNSMASQ_LISTENING: "all"
      REV_SERVER: "{{ pihole_rev_server }}"
      REV_SERVER_DOMAIN: "{{ pihole_rev_server_domain }}"
      REV_SERVER_TARGET: "{{ pihole_rev_server_target }}"
      REV_SERVER_CIDR: "{{ pihole_rev_server_cidr }}"
    dns_servers:
      - 127.0.0.1
      - "{{ static_dns }}"
    network_mode: host
    volumes:
      - /home/pi/pihole/pihole/:/etc/pihole/
      - /home/pi/pihole/dnsmasq.d/:/etc/dnsmasq.d/
    log_driver: json-file
    log_options:
      max-size: "10m"
      max-file: "5"

- name: Check pihole container
  uri:
    url: http://localhost
  register: result
  until: result.status == 200
  retries: 5
  delay: 10

- name: Remove old image versions
  docker_prune:
    images: yes
    images_filters:
      dangling: false

- name: ATTENTION!!!
  debug:
    msg:
      - "Make sure to point your DNS server settings to this Pi-hole:"
      - "DNSv4: {{ ansible_host }}"
      - "DNSv6: {{ ipv6 }}"
      - ""
      - "In the HA setup with keepalived, these are your settings:"
      - "DNSv4: {{ pihole_vip_ipv4.split('/')[0] }}"
      - "DNSv6: {{ pihole_vip_ipv6.split('/')[0] }}"
